import React,{useEffect,useState} from 'react';
import {SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useLocalSearchParams} from 'expo-router'; import {supabase} from '@/lib/supabase'; import type{Tasting} from '@/lib/types'; import {CompareRadarChart,COMPARE_COLORS} from '@/components/CompareRadarChart';
export default function Compare(){
 const{ids=''}=useLocalSearchParams<{ids?:string}>(); const[items,setItems]=useState<Tasting[]>([]);
 useEffect(()=>{const a=String(ids).split(',').filter(Boolean);if(a.length)supabase.from('tastings').select('*').in('id',a).then(({data})=>setItems((data||[]) as Tasting[]))},[ids]);
 return <SafeAreaView style={s.wrap}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Compare Wines</Text><View style={{alignItems:'center'}}><CompareRadarChart items={items}/></View><View style={s.grid}>{items.map((t,i)=><View key={t.id} style={s.card}><View style={[s.dot,{backgroundColor:COMPARE_COLORS[i%COMPARE_COLORS.length]}]}/><Text style={s.wine}>{t.name} {t.vintage}</Text><Text style={s.meta}>{t.varietals.join(', ')}</Text><Text style={s.meta}>{[t.vineyard,t.region,t.country].filter(Boolean).join(' · ')}</Text>{[['Rating',t.rating||'—'],['Quality',t.quality],['Acidity',t.acidity],['Tannin',t.tannin],['Alcohol',t.alcohol],['Body',t.body],['Finish',t.finish],['Complexity',t.complexity]].map(([k,v])=><View key={String(k)} style={s.metric}><Text>{k}</Text><Text style={{fontWeight:'800'}}>{String(v)}</Text></View>)}</View>)}</View></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#f6f3ef'},content:{padding:16,paddingBottom:50},title:{fontSize:28,fontWeight:'800',marginBottom:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},card:{width:260,backgroundColor:'#fffdf9',borderWidth:1,borderColor:'#ded6d0',borderRadius:14,padding:12},dot:{width:12,height:12,borderRadius:99,marginBottom:6},wine:{fontSize:16,fontWeight:'800'},meta:{color:'#756c67',marginTop:2},metric:{flexDirection:'row',justifyContent:'space-between',paddingVertical:5,borderTopWidth:1,borderTopColor:'#eee6e1',marginTop:4}});
