import React,{useCallback,useMemo,useState} from 'react';
import {Alert,FlatList,Platform,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View} from 'react-native';
import {router,useFocusEffect} from 'expo-router'; import {supabase} from '@/lib/supabase'; import type{Tasting} from '@/lib/types'; import * as FileSystem from 'expo-file-system/legacy'; import * as Sharing from 'expo-sharing';
export default function Library(){
 const[items,setItems]=useState<Tasting[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<string[]>([]);
 const load=useCallback(async()=>{const{data,error}=await supabase.from('tastings').select('*').order('tasting_date',{ascending:false});if(error)Alert.alert('Could not load',error.message);setItems((data||[]) as Tasting[])},[]); useFocusEffect(useCallback(()=>{load()},[load]));
 const filtered=useMemo(()=>{const x=q.toLowerCase().trim();return items.filter(t=>!x||[t.name,t.vintage,t.region,t.vineyard,t.country,t.wine_type,t.varietals.join(' ')].join(' ').toLowerCase().includes(x))},[items,q]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 async function exportCsv(){const cols=['name','vintage','wine_type','varietals','region','vineyard','country','tasting_date','rating','quality','acidity','tannin','alcohol','body','finish','complexity','primary_notes','secondary_notes','tertiary_notes','palate_notes','conclusion'];const esc=(v:any)=>`"${String(Array.isArray(v)?v.join('; '):(v??'')).replace(/"/g,'""')}"`;const csv=[cols.join(','),...filtered.map(r=>cols.map(c=>esc((r as any)[c])).join(','))].join('\n');if(Platform.OS==='web'){const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='wine-tastings.csv';a.click();URL.revokeObjectURL(url)}else{const uri=FileSystem.cacheDirectory+'wine-tastings.csv';await FileSystem.writeAsStringAsync(uri,csv);if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'text/csv'})}}
 return <SafeAreaView style={s.wrap}><View style={s.head}><View><Text style={s.title}>My Tastings</Text><Text style={s.sub}>{items.length} saved</Text></View><View style={s.actions}><Pressable style={s.secondary} onPress={exportCsv}><Text>Export CSV</Text></Pressable>{!!selected.length&&<Pressable style={s.secondary} onPress={()=>router.push({pathname:'/compare',params:{ids:selected.join(',')}})}><Text>Compare ({selected.length})</Text></Pressable>}<Pressable style={s.primary} onPress={()=>router.push('/tasting')}><Text style={s.pt}>＋ New</Text></Pressable></View></View><TextInput style={s.search} placeholder="Search wine, grape, region, vineyard…" value={q} onChangeText={setQ}/><FlatList data={filtered} keyExtractor={x=>x.id!} contentContainerStyle={{padding:16,gap:10}} renderItem={({item})=><View style={s.card}><View style={s.cardTop}><Pressable style={[s.check,selected.includes(item.id!)&&s.checkOn]} onPress={()=>toggle(item.id!)}><Text style={selected.includes(item.id!)?{color:'#fff'}:undefined}>{selected.includes(item.id!)?'✓':'+'}</Text></Pressable><Pressable style={{flex:1}} onPress={()=>router.push({pathname:'/tasting',params:{id:item.id}})}><Text style={s.wine}>{item.name||'Unnamed wine'} {item.vintage}</Text><Text style={s.meta}>{item.varietals.join(', ')||'Unknown varietal'}</Text><Text style={s.meta}>{[item.vineyard,item.region,item.country].filter(Boolean).join(' · ')}</Text><Text style={s.rating}>{item.rating?item.rating+'/100':item.quality}</Text></Pressable></View></View>} ListEmptyComponent={<Text style={{padding:16,color:'#756c67'}}>No tastings yet.</Text>}/></SafeAreaView>;
}
const s=StyleSheet.create({wrap:{flex:1,backgroundColor:'#f6f3ef'},head:{padding:16,paddingTop:24,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},title:{fontSize:28,fontWeight:'800'},sub:{color:'#756c67'},search:{marginHorizontal:16,borderWidth:1,borderColor:'#ded6d0',backgroundColor:'#fff',padding:12,borderRadius:12},card:{backgroundColor:'#fffdf9',borderWidth:1,borderColor:'#ded6d0',borderRadius:15,padding:15},cardTop:{flexDirection:'row',gap:12},check:{width:34,height:34,borderWidth:1,borderColor:'#ded6d0',borderRadius:8,alignItems:'center',justifyContent:'center'},checkOn:{backgroundColor:'#6f2136',borderColor:'#6f2136'},wine:{fontSize:17,fontWeight:'800'},meta:{color:'#756c67',marginTop:3},rating:{fontWeight:'800',color:'#6f2136',marginTop:8},primary:{backgroundColor:'#6f2136',padding:10,borderRadius:10},pt:{color:'#fff',fontWeight:'700'},secondary:{backgroundColor:'#efe8e2',padding:10,borderRadius:10}});
