import React,{useEffect,useState} from 'react';
import {Alert,Image,Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import Slider from '@react-native-community/slider'; import * as ImagePicker from 'expo-image-picker'; import {router,useLocalSearchParams} from 'expo-router';
import {supabase} from '@/lib/supabase'; import {COLORS,GRAPES,REGION_COUNTRY,VINEYARDS} from '@/data/wine'; import type{Tasting} from '@/lib/types'; import {RadarChart} from '@/components/RadarChart'; import {COLOR_THEMES,DEFAULT_THEME} from '@/lib/theme'; import {signedPhotoUrl,uploadPrivatePhoto} from '@/lib/photos';
const blank:Tasting={name:'',vintage:'',wine_type:'Red',varietals:[],region:'',vineyard:'',country:'',tasting_date:new Date().toISOString().slice(0,10),pre_notes:'',clarity:'Clear',appearance_intensity:'Medium',color:'Ruby',nose_condition:'Clean',nose_intensity:3,development:'Youthful',primary_notes:'',secondary_notes:'',tertiary_notes:'',sweetness:'Dry',flavor_intensity:3,acidity:3,tannin:3,alcohol:3,body:3,finish:3,complexity:3,tannin_texture:'',mousse:'N/A',palate_notes:'',quality:'Good',readiness:'Drink now; can age',rating:null,buy_again:'Yes',conclusion:''};
function Chips({items,value,onChange,accent}:{items:string[],value:string[],onChange:(v:string[])=>void,accent:string}){return <View style={s.chips}>{items.map(x=><Pressable key={x} style={[s.chip,value.includes(x)&&{backgroundColor:accent,borderColor:accent}]} onPress={()=>onChange(value.includes(x)?value.filter(v=>v!==x):[...value,x])}><Text style={value.includes(x)?s.chipOnTxt:s.chipTxt}>{x}</Text></Pressable>)}</View>}
function Choice({label,value,items,onChange,accent}:{label:string,value:string,items:string[],onChange:(v:string)=>void,accent:string}){return <View><Text style={s.label}>{label}</Text><Chips items={items} value={value?[value]:[]} onChange={v=>onChange(v[v.length-1]||'')} accent={accent}/></View>}
function Scale({label,value,onChange,accent}:{label:string,value:number,onChange:(v:number)=>void,accent:string}){return <View style={{marginBottom:10}}><View style={s.rb}><Text style={s.label}>{label}</Text><Text style={[s.score,{color:accent}]}>{value}</Text></View><Slider minimumValue={1} maximumValue={5} step={1} value={value} onValueChange={onChange} minimumTrackTintColor={accent}/></View>}
export default function TastingScreen(){
 const{id}=useLocalSearchParams<{id?:string}>(); const[t,setT]=useState<Tasting>(blank),[saving,setSaving]=useState(false),[bottle,setBottle]=useState<string|null>(null),[label,setLabel]=useState<string|null>(null); const theme=COLOR_THEMES[t.color]||DEFAULT_THEME; const up=(k:keyof Tasting,v:any)=>setT(p=>({...p,[k]:v}));
 useEffect(()=>{if(!id)return;supabase.from('tastings').select('*').eq('id',id).single().then(async({data})=>{if(data){const r=data as Tasting;setT(r);setBottle(await signedPhotoUrl(r.photo_url));setLabel(await signedPhotoUrl(r.label_photo_url))}})},[id]);
 const radar=[t.acidity,t.tannin,t.alcohol,t.body,Math.round((t.nose_intensity+t.flavor_intensity)/2),t.finish,t.complexity];
 async function save(){setSaving(true);const{data:{user}}=await supabase.auth.getUser();if(!user){setSaving(false);return router.replace('/login')}const payload={...t,user_id:user.id,updated_at:new Date().toISOString()};const r=t.id?await supabase.from('tastings').update(payload).eq('id',t.id).select().single():await supabase.from('tastings').insert(payload).select().single();setSaving(false);if(r.error)return Alert.alert('Could not save',r.error.message);setT(r.data as Tasting)}
 async function ensureSaved(){if(t.id)return t;const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Not signed in');const{data,error}=await supabase.from('tastings').insert({...t,user_id:user.id}).select().single();if(error)throw error;setT(data as Tasting);return data as Tasting}
 async function photo(kind:'bottle'|'label',camera:boolean){try{const perm=camera?await ImagePicker.requestCameraPermissionsAsync():await ImagePicker.requestMediaLibraryPermissionsAsync();if(!perm.granted)return Alert.alert('Permission needed');const r=camera?await ImagePicker.launchCameraAsync({quality:.8}):await ImagePicker.launchImageLibraryAsync({quality:.8});if(r.canceled)return;const row=await ensureSaved();const{data:{user}}=await supabase.auth.getUser();if(!user||!row.id)return;const path=await uploadPrivatePhoto(r.assets[0].uri,user.id,row.id,kind),field=kind==='bottle'?'photo_url':'label_photo_url';await supabase.from('tastings').update({[field]:path}).eq('id',row.id);up(field as keyof Tasting,path);const url=await signedPhotoUrl(path);kind==='bottle'?setBottle(url):setLabel(url)}catch(e:any){Alert.alert('Photo upload failed',e.message||String(e))}}
 function webNotes(){if(!t.name)return Alert.alert('Enter the wine name first');const q=[`"${t.name}"`,t.vintage!=='NV'?t.vintage:'',t.region,t.varietals.join(' '),'"tasting notes"'].filter(Boolean).join(' ');Linking.openURL('https://www.google.com/search?q='+encodeURIComponent(q))}
 return <SafeAreaView style={[s.wrap,{backgroundColor:theme.bg}]}><ScrollView contentContainerStyle={s.content}><View style={s.top}><Pressable style={[s.secondary,{backgroundColor:theme.soft}]} onPress={()=>router.back()}><Text>← Library</Text></Pressable><View style={s.row}><Pressable style={[s.secondary,{backgroundColor:theme.soft}]} onPress={webNotes}><Text>Web Notes</Text></Pressable><Pressable style={[s.primary,{backgroundColor:theme.accent}]} onPress={save}><Text style={s.pt}>{saving?'Saving…':'Save'}</Text></Pressable></View></View>
 <Section title="Wine" card={theme.card} line={theme.line}><Text style={s.label}>Wine / Producer</Text><TextInput style={s.input} value={t.name} onChangeText={v=>up('name',v)}/><Text style={s.label}>Vintage</Text><View style={s.row}><TextInput style={[s.input,{flex:1}]} value={t.vintage} onChangeText={v=>up('vintage',v)} placeholder="2022 or NV"/><Pressable style={[s.secondary,{backgroundColor:theme.soft}]} onPress={()=>up('vintage','NV')}><Text>NV</Text></Pressable></View><Choice label="Wine type" value={t.wine_type} items={['Red','White','Rose','Sparkling','Fortified','Orange / Skin-contact']} accent={theme.accent} onChange={v=>{up('wine_type',v);up('color',COLORS[v]?.[0]||'')}}/><Choice label="Color" value={t.color} items={COLORS[t.wine_type]||[]} accent={theme.accent} onChange={v=>up('color',v)}/><Text style={s.label}>Varietals</Text><Chips items={GRAPES} value={t.varietals} accent={theme.accent} onChange={v=>up('varietals',v.includes('Unknown')?['Unknown']:v.filter(x=>x!=='Unknown'))}/><Text style={s.label}>Region / Appellation</Text><Chips items={Object.keys(REGION_COUNTRY)} value={t.region?[t.region]:[]} accent={theme.accent} onChange={v=>{const r=v[v.length-1]||'';setT(p=>({...p,region:r,country:REGION_COUNTRY[r]||p.country,vineyard:''}))}}/>{!!(VINEYARDS[t.region]||[]).length&&<><Text style={s.label}>Vineyard / Site</Text><Chips items={VINEYARDS[t.region]} value={t.vineyard?[t.vineyard]:[]} accent={theme.accent} onChange={v=>up('vineyard',v[v.length-1]||'')}/></>}<TextInput style={s.input} value={t.vineyard} onChangeText={v=>up('vineyard',v)} placeholder="Or type vineyard/site"/><Text style={s.label}>Country</Text><TextInput style={s.input} value={t.country} onChangeText={v=>up('country',v)}/><Pressable style={[s.secondary,{backgroundColor:theme.soft}]} onPress={()=>t.region?router.push({pathname:'/map',params:{region:t.region,vineyard:t.vineyard,country:t.country}}):Alert.alert('Choose a region first')}><Text>🗺 Terrain Map</Text></Pressable><Text style={s.label}>Pre-tasting notes</Text><TextInput multiline style={[s.input,s.area]} value={t.pre_notes} onChangeText={v=>up('pre_notes',v)}/></Section>
 <Section title="Appearance" card={theme.card} line={theme.line}><Choice label="Clarity" value={t.clarity} items={['Clear','Hazy']} accent={theme.accent} onChange={v=>up('clarity',v)}/><Choice label="Intensity" value={t.appearance_intensity} items={['Pale','Medium','Deep']} accent={theme.accent} onChange={v=>up('appearance_intensity',v)}/></Section>
 <Section title="Nose" card={theme.card} line={theme.line}><Choice label="Condition" value={t.nose_condition} items={['Clean','Unclean / possible fault']} accent={theme.accent} onChange={v=>up('nose_condition',v)}/><Scale label="Aroma intensity" value={t.nose_intensity} onChange={v=>up('nose_intensity',v)} accent={theme.accent}/><Choice label="Development" value={t.development} items={['Youthful','Developing','Fully developed','Past its best']} accent={theme.accent} onChange={v=>up('development',v)}/><Text style={s.label}>Primary aromas</Text><TextInput multiline style={[s.input,s.area]} value={t.primary_notes} onChangeText={v=>up('primary_notes',v)}/><Text style={s.label}>Secondary aromas</Text><TextInput multiline style={[s.input,s.area]} value={t.secondary_notes} onChangeText={v=>up('secondary_notes',v)}/><Text style={s.label}>Tertiary aromas</Text><TextInput multiline style={[s.input,s.area]} value={t.tertiary_notes} onChangeText={v=>up('tertiary_notes',v)}/></Section>
 <Section title="Palate" card={theme.card} line={theme.line}><Choice label="Sweetness" value={t.sweetness} items={['Dry','Off-dry','Medium-dry','Medium-sweet','Sweet','Luscious']} accent={theme.accent} onChange={v=>up('sweetness',v)}/><Scale label="Flavor intensity" value={t.flavor_intensity} onChange={v=>up('flavor_intensity',v)} accent={theme.accent}/><Scale label="Acidity" value={t.acidity} onChange={v=>up('acidity',v)} accent={theme.accent}/><Scale label="Tannin" value={t.tannin} onChange={v=>up('tannin',v)} accent={theme.accent}/><Scale label="Alcohol" value={t.alcohol} onChange={v=>up('alcohol',v)} accent={theme.accent}/><Scale label="Body" value={t.body} onChange={v=>up('body',v)} accent={theme.accent}/><Scale label="Finish" value={t.finish} onChange={v=>up('finish',v)} accent={theme.accent}/><Scale label="Complexity" value={t.complexity} onChange={v=>up('complexity',v)} accent={theme.accent}/><Text style={s.label}>Tannin texture</Text><TextInput style={s.input} value={t.tannin_texture} onChangeText={v=>up('tannin_texture',v)}/><Choice label="Mousse" value={t.mousse} items={['N/A','Delicate','Creamy','Aggressive']} accent={theme.accent} onChange={v=>up('mousse',v)}/><Text style={s.label}>Palate notes</Text><TextInput multiline style={[s.input,s.area]} value={t.palate_notes} onChangeText={v=>up('palate_notes',v)}/><View style={{alignItems:'center'}}><RadarChart values={radar} stroke={theme.accent}/></View></Section>
 <Section title="Conclusions" card={theme.card} line={theme.line}><Choice label="Quality" value={t.quality} items={['Faulty','Poor','Acceptable','Good','Very good','Outstanding']} accent={theme.accent} onChange={v=>up('quality',v)}/><Choice label="Readiness / ageing" value={t.readiness} items={['Too young','Drink now; can age','Drink now; limited ageing benefit','Past its best']} accent={theme.accent} onChange={v=>up('readiness',v)}/><Text style={s.label}>Personal rating / 100</Text><TextInput style={s.input} keyboardType="number-pad" value={t.rating?.toString()||''} onChangeText={v=>up('rating',v?Number(v):null)}/><Choice label="Would buy again?" value={t.buy_again} items={['Yes','Maybe','No']} accent={theme.accent} onChange={v=>up('buy_again',v)}/><Text style={s.label}>Final conclusion</Text><TextInput multiline style={[s.input,s.area]} value={t.conclusion} onChangeText={v=>up('conclusion',v)}/></Section>
 <Section title="Photos" card={theme.card} line={theme.line}><Photo title="Bottle / wine" uri={bottle} soft={theme.soft} onCam={()=>photo('bottle',true)} onLib={()=>photo('bottle',false)}/><Photo title="Label" uri={label} soft={theme.soft} onCam={()=>photo('label',true)} onLib={()=>photo('label',false)}/></Section><Pressable style={[s.primary,{backgroundColor:theme.accent,marginTop:16}]} onPress={save}><Text style={s.pt}>Save Tasting</Text></Pressable>
 </ScrollView></SafeAreaView>;
}
function Section({title,children,card,line}:{title:string,children:React.ReactNode,card:string,line:string}){return <View style={[s.section,{backgroundColor:card,borderColor:line}]}><Text style={s.h1}>{title}</Text>{children}</View>}
function Photo({title,uri,onCam,onLib,soft}:{title:string,uri:string|null,onCam:()=>void,onLib:()=>void,soft:string}){return <View style={{marginBottom:18}}><Text style={s.label}>{title}</Text>{uri?<Image source={{uri}} style={s.photo}/>:<View style={s.photoEmpty}><Text style={{color:'#756c67'}}>No photo yet</Text></View>}<View style={s.row}><Pressable style={[s.secondary,{backgroundColor:soft}]} onPress={onCam}><Text>Camera</Text></Pressable><Pressable style={[s.secondary,{backgroundColor:soft}]} onPress={onLib}><Text>Photo Library</Text></Pressable></View></View>}
const s=StyleSheet.create({wrap:{flex:1},content:{padding:16,maxWidth:920,width:'100%',alignSelf:'center',paddingBottom:80},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{borderWidth:1,borderRadius:16,padding:16,marginTop:12},h1:{fontSize:22,fontWeight:'800',marginBottom:10},label:{fontSize:12,fontWeight:'800',color:'#756c67',textTransform:'uppercase',marginTop:8,marginBottom:5},input:{borderWidth:1,borderColor:'#ded6d0',borderRadius:10,padding:11,backgroundColor:'#fff',marginBottom:8},area:{minHeight:88,textAlignVertical:'top'},row:{flexDirection:'row',gap:8,alignItems:'center'},rb:{flexDirection:'row',justifyContent:'space-between'},primary:{padding:12,borderRadius:10,alignItems:'center'},pt:{color:'#fff',fontWeight:'800'},secondary:{padding:11,borderRadius:10,alignItems:'center'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7,marginBottom:8},chip:{borderWidth:1,borderColor:'#ded6d0',backgroundColor:'#fff',paddingHorizontal:10,paddingVertical:7,borderRadius:999},chipTxt:{fontSize:13},chipOnTxt:{fontSize:13,color:'#fff',fontWeight:'700'},score:{fontWeight:'800'},photo:{width:'100%',height:260,borderRadius:12,resizeMode:'contain',backgroundColor:'#f1ece8'},photoEmpty:{height:150,borderWidth:1,borderStyle:'dashed',borderColor:'#cfc5bf',borderRadius:12,alignItems:'center',justifyContent:'center',marginBottom:8}});
